version: '3'
services:
  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/metricsdb
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  agent:
    build: ./agent
    depends_on:
      - backend

volumes:
  mongo_data:
